### ISSUE TITLE
Enhancement ToLabel with automatic multi lines

### ISSUE THREAD

**Issue by LANDAISB** [plantec/Toplo#135]
We have a need of a multi-lines label widget who can display text using the whole space, like a read-only TextArea.

Basically, a ToLabel multiLine but without explicit carrier return, automatically adapting to widget size.

**Comment by labordep** [comment]
Use case example:

![image](https://github.com/pharo-graphics/Toplo/assets/49183340/4ec20846-c4dd-4cf6-9ba3-f980e1288861)

**Comment by labordep** [comment]
With less size: 

![image](https://github.com/pharo-graphics/Toplo/assets/49183340/8897b094-b40d-4ff6-a944-372849d4ed88)

**Comment by labordep** [comment]
May be this is not a ToLabel but another widget as ToText ?

**Comment by plantec** [comment]
Is is ok with a ToTextField ?

example:
ToTextField new withLineWrapping; text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur varius felis finibus congue porttitor. Integer vehicula risus at odio porttitor semper. Aliquam erat volutpat. Curabitur feugiat tellus vitae massa interdum, ac ultrices dui scelerisque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla facilisi. In pulvinar dui lectus, vel
auctor purus fermentum id.'; beReadonlyWithoutSelection; openInInnerWindow

**Comment by plantec** [comment]
```
initializeToTextFieldStyleRules

	| fontName |
	fontName := 'American Typewriter'.

	self select: ToTextField asTypeSelector style: [

		self select: #description asStampSelector style: [
			self when: ToInstallLookEvent write: (self property: #'text-attributes-with-builder') with: [:e |
				e textAttributesBuilder fontSize: (self getFontSize: 25).
				e textAttributesBuilder defaultFontName: fontName.
				e textAttributesBuilder light.
				e textAttributesBuilder foreground: (Color red).
			].
		].
	]```

**Comment by plantec** [comment]
this should work now with my last commit (Toplo:dev)
