### ISSUE TITLE
Button API seems unfriendly for changing click action

### ISSUE THREAD

**Issue by tinchodias** [plantec/Toplo#44]
This is because whenClickedDo adds a new event handler for click each time. Example:
```smalltalk
| but lab ico pane |
pane := ToPane new.
lab := ToLabel new text: 'Button'; yourself.
ico := ToImage inner: (self iconNamed: #remove).
pane addChildren: { ico. lab }.
but := ToGeneralButton new
	dresser: ToGeneralButtonDresser new;
	addChild: pane;
	whenClickedDo: [ self inform: '1' ];
	whenClickedDo: [ self inform: '2' ];
	yourself.
but openInOBlSpace 
```
it pop ups 2 messages each time.

**Comment by plantec** [comment]
In general, the whenXXXXDo: pattern leads to this kind of issue.
I have to think about it

**Comment by tinchodias** [comment]
A possible solution: the button has in initialize:
```
action := [].
self whenClickedDo: [ action value ]
```
and it's prepared to somebody that updates the valuable via `action:`. And there is a single "official action" of the button.

**Comment by plantec** [comment]
the event handler is now stored so that it can be replaced or removed
