### ISSUE TITLE
ToCheckbox startIndeterminate fail, ToCheckbox indeterminate  works

### ISSUE THREAD

**Issue by rvillemeur** [plantec/Toplo#45]
ToCheckbox new startUnchecked  openInWorld => works as expected (an unchecked chexbox in a new window)
ToCheckbox new startChecked   openInWorld => works as expected (a checked chexbox in a new window)

ToCheckbox new startIndeterminate openInWorld => fail with message: "instance of ToCheckbox did not understand #counter"
ToCheckBox new indeterminate work, but its appearance does not match the result I can see in ToCheckBoxDresser >> defaultIndeterminateIconImage

**Comment by plantec** [comment]
Thanks! This raised several issues and a bad design.
Last commit should fixe all what your reported

**Comment by plantec** [comment]
I added ToCheckboxTest that checks theses issues
