### ISSUE TITLE
Examples crashing 

### ISSUE THREAD

**Issue by Enzo-Demeulenaere** [plantec/Toplo#46]
Hello, I was looking to discover Toplo with some examples in the class *ToSandBox* but few of them were crashing and I couldn't see those examples.

Here's a snippet to help you find these examples: 

```SmallTalk

| l sels |
l := OrderedCollection new.
sels := ToSandBox class selectors.

sels do: [ :i |
		| res |
		res := [ToSandBox perform: i] on: Error do: [ l add: i ]].

l inspect

```

And here's the list of selectors that crashed for me (found with the snippet): 

```SmallTalk
#example_EditorWithPlaceholder
#example_EditorWithSoftLine 
#example_toAlbumAsButton 
#example_CodeEditorWithToAlbumModel 
#example_textFieldWithPlaceholder 
#example_textFieldWithSaveCapability 
#example_InlineAutocompleteComboBoxWithStatesOfAmerica 
#example_toPairWithColumn1 
#example_textFieldWithPlaceholder2 
#example_FilterOnListWithAllClassesAndTraitsSorted 
#example_textFieldWithLineWrapping 
#example_textFieldWithoutLineWrapping
#example_menu6 
#example_toPairJustified2 
#example_EditorWithoutSoftLine 
#example_textFieldWithLineWrappingWithSaveCapability 
#example_EditorWithPlaceholderWithToAlbumModel 
#example_anchoredWidow1 
#example_rootFrameWithContextMenu 
#example_textField0
```

**Comment by plantec** [comment]
thanks.
some of these example used 'space addChild: bla' instead of 'space root addChild: bla'.
this is fixed. 
but other examples that you mention are working well here.

what is your configuration ?

**Comment by Enzo-Demeulenaere** [comment]
Ok nevermind I was some commits behind on Bloc and it seems to be working now thanks a lot

**Comment by plantec** [comment]
thanks Enzo, don't hesitate to contribute :) you can push PRs
